---
title: "Rapport de Stage/Recherche"
author: "Valentin Frappier"
date: "26/05/2021"
output:
  html_document: default
  pdf_document: default
---

# Rapport de Recherche : Sur la sélection des intervalles de confiance

## Introduction

Le but de ce rapport est d'exhiber la non unicité des intervalles de confiance, et de traiter de la question de "meilleur" parmis ces intervalles dans le cas de variables aléatoires pivotales de distributions symétriques, et non symétriques. Dans cette introduction, on rapellera les différentes définitions utiles pour traiter la question, puis on rapellera la méthode de construction des IC avant d'introduire un premier questionnement.

### 1) Rappels et Définitions:

Soit $X$ une variable aléatoire suivant une certaine loi $Y(\theta)$ où $\theta$ est un paramètre que l'on cherche à estimer. Soit $(X_1...X_n)$ un n-échantillon de v.a indépendantes et identiquement distribuées de même loi que $X$ : $(X_1,...,X_n) \sim iid \ Y(\theta)$

Un intervalle de confiance est un intervalle où la valeur de $\theta$ a de bonne chance de se trouver.

Une variable aléatoire $T$ est qualifiée de pivotale pour $\theta$ si :

-   $T$ est une fonction qui ne dépend que du n-échantillon et de $\theta$, i.e une fois le n-échantillon observé, la v.a pivotale $T$ dépend uniquement de $\theta$.

-   La loi de probabilité de $T$ ne dépend pas de $\theta$.

### 2) Construction d'un intervalle de confiance

L'existance d'une variable aléatoire $T$ pivotale pour $\theta$ facilite grandement la construction d'un intervalle de confiance. En effet, un encadrement de $T$ au niveau $1-\alpha$ nous est donné par la formule vue en cours :

$$ \mathrm{P}(q_\frac{\alpha}{2} \le T(\theta,X_1,...,X_n) \le q_{1-\frac{\alpha}{2}} ) = 1-\alpha $$ en appelant $\alpha$ la probabilité de commettre une erreur de type I et où $q_\alpha$ est le quantile d'ordre $\alpha$ de la distribution de $T$. Cet encadrement nous permet donc de proposer l'intervalle de confiance pour $\theta$ de niveau $1-\alpha$ suivant : $$ IC_{1-\alpha}(\theta) = [T^{-1}(q_\frac{\alpha}{2}) \ ; \ T^{-1}(q_{1-\frac{\alpha}{2}})]$$

Prenons un exemple typique : Soit $X$ une variable aléatoire telle que $X\sim {\sf Norm} (\mu,\sigma ^ 2)$. Une étude a été menée et on a observé les valeurs $(x_1,...,x_n)$ d'un n-échantillon $(X_1,...,X_n) \sim iid \ X$.

Supposons par exemple vouloir estimer la moyenne $\mu$ de la distribution de $X$ en connaisant la valeur de $\sigma$ : $\sigma$ = $\sigma_0$. Une v.a. pivotale pour $\mu$ nous est donné par le TCL : $Z = \sqrt n \frac{\overline{X_n} - \mu}{\sigma_0}$ et $Z\sim{\sf Norm}(0,1)$

Par la formule précédemment énnoncée, on a :

$\mathrm{P}(z_\frac{\alpha}{2} \le Z(\mu,X_1,...,X_n) \le z_{1-\frac{\alpha}{2}} ) = 1-\alpha$

$\Leftrightarrow \mathrm{P}(z_\frac{\alpha}{2} \le \sqrt n \ \frac{\overline{X_n} - \mu}{\sigma_0} \le z_{1-\frac{\alpha}{2}} ) = 1-\alpha$

$\Leftrightarrow \mathrm{P}(-\ z_{1-\frac{\alpha}{2}} \le \sqrt n \ \frac{ \mu - \overline{X_n}}{\sigma_0} \le -\ z_\frac{\alpha}{2}) = 1-\alpha$

$\Leftrightarrow \mathrm{P}( \overline{X_n} - \frac{\sigma_0}{\sqrt n}\ z_{1-\frac{\alpha}{2}} \le \mu\le \overline{X_n} - \frac{\sigma_0}{\sqrt n}\ z_{\frac{\alpha}{2}})= 1-\alpha$

La distribution de Z (loi normale centré réduite) étant une loi symétrique, alors on a la relation $-z_\frac{\alpha}{2} = z_{1-\frac{\alpha}{2}}$

Ainsi : $\mathrm{P}( \overline{X_n} - \frac{\sigma_0}{\sqrt n}\ z_{1-\frac{\alpha}{2}} \le \mu\le \overline{X_n} + \frac{\sigma_0}{\sqrt n}\ z_{1-\frac{\alpha}{2}})= 1-\alpha$ ce qui nous amène à proposer l'intervalle de confiance pour $\mu$ de niveau $1-\alpha$ suivant : $$ IC_{1-\alpha}(\mu) = [ \overline{X_n} - \frac{\sigma_0}{\sqrt n}\ z_{1-\frac{\alpha}{2}} \ ;\overline{X_n} + \frac{\sigma_0}{\sqrt n}\ z_{1-\frac{\alpha}{2}}]$$

### 3) Premier questionnement

Il convient donc d'affirmer qu'il est aisé de construire des intervalles de confiances de niveau $1-\alpha$ grâce à la méthode ci-dessus. Mais d'où vient cette fameuse égalité : $\mathrm{P}(q_\frac{\alpha}{2} \le T(\theta,X_1,...,X_n) \le q_{1-\frac{\alpha}{2}} ) = 1-\alpha$ ?

Par définition d'une densité de probabilité, pour toute v.a. continue $T$ , $\mathrm{P}(-\infty \le T\le \infty) = 1$. Prenons l'exemple d'une loi normale centrée réduite :

*(insérer schéma)*

Par propriété des densités de probabilités, l'aire sous la courbe est 1. Pour obtenir l'égalité $\mathrm{P}(L \le T\le U) = 1-\alpha$, on conviendra qu'il suffit de retrancher $\alpha /2$ des deux côtés de la distribution pour avoir une aire sous la courbe de $1-\alpha$ ce qui explique que $\mathrm{P}(q_\frac{\alpha}{2} \le T(\theta,X_1,...,X_n) \le q_{1-\frac{\alpha}{2}} ) = 1-\alpha$.

Mais est-ce là le seul moyen d'obtenir un encadrement de $T$ au niveau $1-\alpha$? Graphiquement, est-ce le seul découpage de l'aire sous la courbe possible pour avoir une aire de $1-\alpha$? Ce qui revient à se poser la question : les bornes L et U sont-elles uniques?

On se convaincra assez rapidement que la réponse à ces question est non, comme peut l'illustrer le schéma suivant :

*(insérer schéma)*

En effet on remarque qu'il suffit de retrancher d'un côté une certaine aire A et de la rajuter de l'autre côté pour avoir encore une aire centrale de $1-\alpha$ , tout en ayant des quantiles différents pour encadrer $T$.Cet exemple simple nous permet de mettre en lumière la proposition suivante : Il n'y a pas unicité des intervalles de confiances.

Mais alors, si on peut construire ce qui semble, à première vue, être une infinité d'intervalles de confiances, on en vient à se demander lequel de tous ces intervalles peut être qualifié de "meilleur", et c'est sur cette question que ce stage va porter.

Encore faudrait-il définir en quoi un intervalle de confiance est "meilleur" qu'un autre. On voit ici 3 critères de comparaison :

-   Le meilleur IC est le plus centré sur le mode (i.e l'intervalle est centré sur la valeur que X a le plus de chance de prendre)

-   Le meilleur IC est celui contenant les valeurs le plus probables de X (hypothèse, :centré sur la moyenne ou sur la médiane)

-   Le meilleur IC est le plus petit (précision de l'estimation du paramètre)

*(insérer schémas des 3 cas)*

Généralisation des intervales de confiances de niveau $1-\alpha$ :

$\mathrm{P}(q_{\lambda\alpha} \le T(\theta,X_1,...,X_n) \le q_{A(\alpha)}) = 1-\alpha$

$\Leftrightarrow A(\alpha)-\lambda\alpha=1-\alpha$

$\Leftrightarrow A(\alpha) = 1-\alpha(1-\lambda)$

D'où la formule d'encadrement : $\mathrm{P}(q_{\lambda\alpha} \le T(\theta,X_1,...,X_n) \le q_{1-\alpha(1-\lambda)} ) = 1-\alpha$ qui nous amène à la formule généralisée d'un intervalle de confiance de niveau $1-\alpha$ :

$$IC_{1-\alpha}(\theta) = [T^{-1}(q_{\lambda\alpha})\ ;\ T^{-1}(q_{1-\alpha(1-\lambda)}) ]$$ On emmet l'hypothèse suivante : Pour une v.a. pivotale $T$ de distribution **symétrique** , le meilleur Intervalle de confiance est obtenu à partir des quantiles d'ordre $\frac{\alpha}{2}$ et $1-\frac{\alpha}{2}$ de la distribution de $T$ donc pour $\lambda = 1/2$.

[**Preuve :**]{.ul}

On supposera dans cette démonstration que $T$ est continue, croissante et linéaire, et que sa distribution est unimodale (un seul pic). On appellera $F$ la fonction de répartition de T et f sa densité de probabilité.

Soit $l_{n,\alpha}(\lambda)$ la longueur de l'intervalle de confiance :

$l_{n,\alpha}(\lambda) = T^{-1}(q_{1-\alpha(1-\lambda)}) - T^{-1}(q_{\lambda\alpha}) = T^{-1}(q_{1-\alpha(1-\lambda)}-q_{\lambda\alpha})$ par linéarité de $T$ donc de $T^{-1}$

$= T^{-1}(-q_{\alpha(1-\lambda)}-q_{\lambda\alpha})$ par symétrie de la distribution de $T$ ($q_x = -q_{1-x}$)

On distingue 3 cas : $\alpha = 0$ , $\alpha=1$ ,et $\alpha\in]0,1[$ .

-   Lorsque $\alpha = 0$, $l_{n,\alpha}(\lambda) = T^{-1}(q_{1}-q_{0})= +\infty$

-   Lorsque $\alpha=1$, $l_{n,\alpha}(\lambda) =T^{-1}(q_{1-1+\lambda)}) - T^{-1}(q_{\lambda}) = 0$

-   Supposons que $\alpha\in]0,1[$ . Alors si $\exists \ \lambda^*$ tel que $\forall \ \lambda \in [0\ ;1]$ : $r(\lambda^*) \le r(\lambda)$, alors par corissance de $T$ donc de $T^{-1}$, $$T^{-1}(r(\lambda^*)) \le T^{-1}(r(\lambda))$$

Ainsi, minimiser $l_{n,\alpha}(\lambda)$, reviens à minimiser :

$g_{\alpha}(\lambda) := - [q_{\alpha(1-\lambda)}+ \ q_{\lambda\alpha}] = - [F^{-1}(\alpha(1-\lambda)) \ +\ F^{-1}(\lambda\alpha))]$

Trouvons un minimum pour $g_{\alpha}(\lambda)$, c'est à dire un maximum pour $h_{\alpha}(\lambda) := F^{-1}(\alpha(1-\lambda)) \ +\ F^{-1}(\lambda\alpha))$. Il est donc de bon goût d'effectuer une recherche d'extrêmas classique : on dérive $h_{\alpha}(\lambda)$ et on résout $\frac{dh_{\alpha}(\lambda)}{d\lambda}=0$

$$
\frac{dh_{\alpha}(\lambda)}{d\lambda}= \frac{dF^{-1}(\alpha(1-\lambda))}{d \lambda} + \frac{dF^{-1}(\lambda\alpha)}{d\lambda}
$$

On se sert de la relation

$FoF^{-1}(x)=x \Leftrightarrow [FoF^{-1}]'(x)=1 \Leftrightarrow F'oF^{-1} \times (F^{-1})'(x) =1 \Leftrightarrow (F^{-1})'(x)= \frac{1}{F'(F^{-1})(x)} = \frac {1}{f(F^{-1})(x)}$ pour obtenir la dérivé de $F^{-1}(x)$ et ainsi l'égalité suivante :

$$
\frac{dh_{\alpha}(\lambda)}{d\lambda}= \frac{\alpha}{f(F^{-1}(\lambda\alpha))} - \frac{\alpha}{f(F^{-1}(\alpha(1-\lambda)))}
$$

$$
= \frac{\alpha[f(F^{-1}(\alpha(1-\lambda)))-f(F^{-1}(\lambda\alpha))]}{f(F^{-1}(\alpha(1-\lambda)))f(F^{-1}(\lambda\alpha))}
$$

Recherche des extrêma :

Comme $\alpha \ge 0$ et $f(x) \ge 0 \ \forall \ x$,

$$
\frac{dh_{\alpha}(\lambda)}{d\lambda}= 0 \Leftrightarrow f(F^{-1}(\alpha(1-\lambda)))-f(F^{-1}(\lambda\alpha)) = 0 \Leftrightarrow f(F^{-1}(\alpha(1-\lambda))) =f(F^{-1}(\lambda\alpha))
$$

Or, puisque la distribution de T est centrée et symétrique, $f(x) = f(y) \Leftrightarrow x = \pm \ y$ donc on a les deux cas suivant :

-   $F^{-1}(\alpha(1-\lambda)) = F^{-1}(\lambda\alpha) \Leftrightarrow \alpha(1-\lambda) = \lambda\alpha \Leftrightarrow 2\lambda = 1 \Leftrightarrow \lambda = 1/2$

-   $F^{-1}(\alpha(1-\lambda)) = -\ F^{-1}(\lambda\alpha) \Leftrightarrow F^{-1}(\alpha(1-\lambda)) = F^{-1}(1-\lambda\alpha) \Leftrightarrow \alpha(1-\lambda) = 1-\lambda\alpha \Leftrightarrow \alpha = 1$ ce qui contredit notre hyphothèse de $\alpha \in ]0 \ ;1[$

Ainsi, $\lambda = 1/2$ est le seul extremum de $h_{\alpha}$ , donc de $g_{\alpha}$ ,donc de $l_{n,\alpha}$ . Montrons maintenant que $\lambda = 1/2$ est un maximum de $h_{\alpha}$ :

$$
\frac{d^2h_{\alpha}(\lambda)}{d\lambda^2} = \frac{\alpha \times[[f(q_{\alpha(1-\lambda)})-f(q_{\lambda\alpha})]'f(q_{\lambda\alpha})f(q_{\alpha(1-\lambda)})-(f(q_{\alpha(1-\lambda)})-f(q_{\lambda\alpha}))([f(q_{\lambda\alpha})]'f(q_{\alpha(1-\lambda)})+[f(q_{\alpha(1-\lambda)})]'f(q_{\lambda\alpha}))]}{[f(q_{\alpha(1-\lambda)})f(q_{\lambda\alpha})]^2}
$$

$$
= \frac{\alpha \times [(f(q_{\alpha(1-\lambda)}))'f(q_{\lambda\alpha})^2-f(q_{\alpha(1-\lambda)})^2(f(q_{\lambda\alpha}))']}{[f(q_{\alpha(1-\lambda)})f(q_{\lambda\alpha})]^2}
$$

On cherche le signe de $\frac{d^2h_{\alpha}(\lambda)}{d\lambda^2}$ évalué en $\lambda=1/2$ :

On a $\alpha \ge 0$ et le dénominateur de $\frac{d^2h_{\alpha}(\lambda)}{d\lambda^2}$ est positif comme carré. Alors, $\frac{d^2h_{\alpha}(\lambda)}{d\lambda^2}$ est de même signe que $(f(q_{\alpha(1-\lambda)}))'f(q_{\lambda\alpha})^2-f(q_{\alpha(1-\lambda)})^2(f(q_{\lambda\alpha}))'$ .

Or, par parité de f,

$$
[f(q_{\alpha(1-\lambda)})]'f(q_{\lambda\alpha})2+f(q_{\alpha(1-\lambda)})2[f(q_{\lambda\alpha})]'=[f(q_{1-\alpha(1-\lambda)})]'f(q_{\lambda\alpha})2-f(q_{1-\alpha(1-\lambda)})2[f(q_{\lambda\alpha})]'
$$

et lorsque $\lambda = 1/2$ ,

$[f(q_{1-\alpha(1-\lambda)})]'f(q_{\lambda\alpha})^2+f(q_{1-\alpha(1-\lambda)})^2[f(q_{\lambda\alpha})]' = [f(q_{1-\frac{\alpha}{2}})]'f(q_{\frac{\alpha}{2}})^2-f(q_{\frac{1-\alpha}{2}})^2[f(q_{\frac{\alpha}{2}})]'$ .

-   $[f(q_{1-\alpha(1-\lambda)})]' < 0$ car $f$ est décroissante sur $]0 \ ; \infty[ \ \ni q_{1-\frac{\alpha}{2}}$

-   $[f(q_{\frac{\alpha}{2}})]'>0$ car $f$ est décroissante sur $]infty \ ; 0[ \ \ni q_{\frac{\alpha}{2}}$

Comme illustré ici : (schéma)

Ainsi, on a $[f(q_{1-\frac{\alpha}{2}})]'f(q_{\frac{\alpha}{2}})^2+f(q_{\frac{1-\alpha}{2}})^2[f(q_{\frac{\alpha}{2}})]'<0$ d'où $\frac{d^2h_{\alpha}(\lambda)}{d\lambda^2}<0$ donc $\lambda=1/2$ est un maximum pour $h_{\alpha}$ et puisque $g_\alpha = - \ h_{\alpha}$ , alors $\lambda=1/2$ est un minimum pour $g_\alpha$ , donc pour $l_{n,\alpha}$ .

Fin de la preuve
